agv_sim:
  gazebo_ros_control:
    pid_gains:
      joint_turn_1: {p: 1.0, i: 0.0, d: 0.0}
      joint_turn_3: {p: 1.0, i: 0.0, d: 0.0}
      joint_wheel_1: {p: 1.0, i: 0.0, d: 0.0}
      joint_wheel_3: {p: 1.0, i: 0.0, d: 0.0}
