oryxbot_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_5
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_6
    pid: {p: 100.0, i: 0.01, d: 10.0}


  gazebo_ros_control:
    pid_gains:
      joint_1: {p: 100.0, i: 0.01, d: 10.0}
      joint_2: {p: 100.0, i: 0.01, d: 10.0}
      joint_5: {p: 100.0, i: 0.01, d: 10.0}
      joint_6: {p: 100.0, i: 0.01, d: 10.0}
      tool_joint: {p: 100.0, i: 0.01, d: 10.0}

 
